### ISSUE TITLE
python-lovelace command hangs

### ISSUE THREAD

**Issue by Billabongodysee** [dale3h/python-lovelace#1]
Hey there, you referred me to this tool from Discord when I was asking about learning lovelace.  I have cloned the repository and installed requirements, however when I run the python lovelace-migrate command "python lovelace_migrate.py -p https://my.domain.com/api" it just hangs and never prompts me for the password.  I also can't quit it with a Ctrl-C. 
Eager to try this tool, thanks for making it.

**Comment by dale3h** [comment]
Hi @Billabongodysee, I pushed an update to the `refactor` branch that should fix the hanging issue. In your terminal change to the `python-lovelace` folder that you cloned, and then make sure that you're on the `refactor` branch. Now run `git pull` and it should pull the latest from GitHub.
